name: Build, test and deploy App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run Client
      run: npm run start &
    - name: Run Server
      run: npm run server &
    - name: Install playwright
      run: npx playwright install 
    - name: Run tests
      run: npm run test

  deploy_fe:

    runs-on: ubuntu-latest
    needs: build_test

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
        - name: Deploy_FE
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.FrontEnd_KEY }}
            api_key: ${{ secrets.Render_KEY }}
            wait_deploy: true 
  
  deploy_be:

    runs-on: ubuntu-latest
    needs: build_test

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
        - name: Deploy_BE
          uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.BackEnd_KEY }}
            api_key: ${{ secrets.Render_KEY }}
            wait_deploy: true 