name: Build, test and deploy App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build the project
      run: npm run build --if-present 
    - name: Run Client
      run: npm start &
    - name: Run Server
      run: nmp run server &
    - name: Install playwright
      run: npx playwright install 
    - name: Run tests
      run: npm test
